services:
  metrix:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./bin/:/db
    environment:
        METRIX_DB: "/db/prod.sqlite"
        METRIX_ADDRESS: ":8080"
